[package]
name = "rmtarget"
version = "0.1.0"
description = "Command line tool to remove target directories recursively"
authors = ["xupremix <xupremix.me@gmail.com>"]
readme = "README.md"
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
